### ISSUE TITLE
Feature request: 'my courses should respect dashboard filter'

### ISSUE THREAD

**Issue by Richardvi** [dbnschools/moodle-theme_schoollege#1]
Hi Chris,

Thanks again for this great theme. We are still on Fordson but will switch to whichever theme you will be maintaining. I like your style!

That said, I have an idea/request. The 'My Courses' menu gets cluttered a lot. Some teachers have around 100 courses in it. I have given it a lot of thought on how to get this organized again.

One idea was that 'my courses' should respect your dashboard setting. If you are looking at the 'starred' courses, or 'current' courses on the dashboard, the 'my courses' should be a reflection of that.

I now tell my teachers to keep a clean dasboard page. To remove courses from their dasboard view that are not used often, not current, etc. However, everything stays in 'My courses'.

Hence my request. I hope this makes sense and I also hope that you can make something like this :)

Thanks in advance,

Richard / HZ University.

**Comment by dbnschools** [comment]
We will need to see how Moodle 4.0 plays out.  I absolutely love the new layout and changes they are making to navigation.  My Courses will actually be a page within Moodle and will make things easy for teachers with large course assignments.  They are going to split Dashboard from My Courses which is perfect and now makes sense.  
If anything, I would include a drop down for "Most Recently Visited" courses and limit it to about 7 courses.  That way, sorting is based automatically on what courses you use most.

Thank you for liking our themes.  Schoollege and Rebel were some things we were experimenting with.  Schoollege really strips down the best aspects of Fordson to get some essential elements unpacked and simplified.

Schoollege will most likely be the base that we build upon for Moodle 4.0.  This is a game changer release with many new navigation improvements.  Most likely it will break things or look funny on most themes.  

I think we all want to see just how all the changes shake out and then work with the new direction that Moodle is going and support it with a super nice looking them wrapped around Boost.

**Comment by Richardvi** [comment]
I agree with you. I'm excited about Moodle 4. That 'most recently visited' menu sounds perfect too btw.

I just want to get rid of the scroll of death in the 'my courses menu'...
